image: node:22

pipelines:
  branches:
    master:
      - step:
          name: Installation & Build App
          caches:
            - node
          script:
            - npm install --legacy-peer-deps
            - npm run build-prod
          artifacts:
            - node_modules/** # Save modules for next steps
            - dist/** # Save build for next steps

      - step:
          name: Deploy
          script:
            - echo "$(ls -la)"
            - echo "$(ls -la dist)"
            - ssh runcloud@memberz.org rm -rf /home/runcloud/webapps/memberz-angular/live/memberz-org
            - scp -r dist/memberz.org runcloud@memberz.org:/home/runcloud/webapps/memberz-angular/live/memberz-org