image: node:14
pipelines:
 branches:
   dev:
     - step:
         caches:
           - node
           - docker
         services:
           - docker
         script:
           - npm install
           - npm run build:production
           - pipe: atlassian/sftp-deploy:0.5.7
             variables:
               USER: $ftp_user
               PASSWORD: $ftp_password
               SERVER: $ftp_host
               REMOTE_PATH: $ftp_remote_path
               LOCAL_PATH: 'dist' #Optional
               DEBUG: 'true' # Optional
               #DELETE_FLAG: 'true' # Optional. This is a option to delete old files before transferring new ones. Default: true.
